version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    environment:
      SA_PASSWORD: "123456aA@"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1433:1433"

  # tedu.api:
  #   container_name: tedu.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - "ConnectionStrings:DefaultConnection=Server=sqlserver;Database=Blog;User Id=sa;Password=123456aA@;Multipleactiveresultsets=true;TrustServerCertificate=True"
  #   depends_on:
  #     - sqlserver
  #   ports:
  #     - "8004:80"
  #   restart: always