version: '3.8'

services:
  #database section
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "123456aA@"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1433:1433"

  idc.api:
    image: ${DOCKER_REGISTRY-}idc.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
     context: .
     dockerfile: IDC.Api/Dockerfile
    container_name: idc.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=sqlserver;Database=IDC;User Id=sa;Password=123456aA@;Multipleactiveresultsets=true;TrustServerCertificate=True;"
      - "ApiConfiguration:IdentityServerBaseUrl=http://localhost:6001"
      - "ApiConfiguration:IssuerUri=http://idp.api"
    depends_on:
      - sqlserver
    ports:
      - '6002:80'
    restart: always

#network section
networks:
  default:
    name: idc_network
    driver: bridge

#volumes sections
volumes:
  sqlserver_data:
    name: sqlserver_data